### ISSUE TITLE
Question About the AP in test set

### ISSUE THREAD

**Issue by yfthu** [SuperMHP/GUPNet#15]
Hello , Thanks for your great work! And we hope to follow your work.
We retrained your code on the KITTI train split (3dop), and evaluate it on the val set, get car's AP in val set: [22.698555, 15.741446, 13.477293], and it is close to your paper's report.
 Then we just use this checkpoint(trained on train split) to infer in KITTI's test set, and submit the result to KITTI benchmark, get the following result in test set:
<img width="386" alt="Untitled picture" src="https://user-images.githubusercontent.com/44047538/154839255-0ec92cbe-98b0-41ae-9eee-84f04b095e5c.png">

The 3D AP is very low(Car's 3D AP: 14.93%, 10.15%, 8.22%). I wonder if it is normal considering the model is trained on train split(not in trainval).

And we want to reproduce your paper's report on KITTI test set, close to car‘s AP（22.26%, 15.02%, 13.12% as your released checkpoint or 20.11%, 14.20%, 11.77% in your original paper）. In addition to setting to the trainval set, what else do we need to do? 
And if I set to trainval set, how do I choose the best checkpoint in case that the val set is included in the trainval set?
Thank you very much for your reply！

**Comment by SuperMHP** [comment]
1. Thanks for your attention. Please mention that when evaluating on the test set, you should train on the trainval set (train set + eval set) rather than on train set. This setting is provided by previous works. So directly using checkpoint from train set is not right. 
2. When you train on trainval set, just use the final one. We have tested 3 times on the test set. The best one is the released ckp. Do not need other ways to select ckp.
