### ISSUE TITLE
The difference between original paper and released ckpt

### ISSUE THREAD

**Issue by aqianwang** [SuperMHP/GUPNet#3]
Dear author,

Thanks for your wonderful work. I am following your repo to build a 3D detection framework. Do you mind telling me the difference between the results of original paper and released ckpt (especially on the test set) . And what causes the performance gap between them?

**Comment by SuperMHP** [comment]
Hi, one difference is: we modify the model to predict variance rather than std. So we avoid the square and square root operation in equation (3). We find that this modification can lead to more stable results because the numerical range is small. Other things include tricks are equal. 

Except that, it also exists a performance jitter between different chkps.

**Comment by aqianwang** [comment]
Got it. Thanks for your reply.
