### ISSUE TITLE
Is the network pretrained on a depth set?

### ISSUE THREAD

**Issue by Cc-Hy** [SuperMHP/GUPNet#5]
Hello, good job.
I notice many methods use a depth pre-training for better performance,
is your network pre-trained on a depth set first?

**Comment by SuperMHP** [comment]
No any pretrain. If you need, you can try to add. 

发件人: Cc
发送时间: 2021年11月1日 22:49
收件人: SuperMHP/GUPNet
抄送: Subscribed
主题: [SuperMHP/GUPNet] Is the network pretrained on a depth set? (Issue#5)

Hello, good job.
I notice many methods use a depth pre-training for better performance,
is your network pre-trained on a depth set first?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Cc-Hy** [comment]
Thanks.
